spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: servicio-mantenimientos
        uri: lb://servicio-mantenimientos
        predicates:
        - Path=/gestion/mantenimientos/**
        filters:
        - StripPrefix=2
      - id: cereales
        uri: lb://servicio-cereales
        predicates:
        - Path=/gestion/**
        filters:
        - StripPrefix=1

          